### PR TITLE
Predicate definitions & evaluate

### PR DESCRIPTION
**Pull request by schillic**
This is my proposal from https://github.com/JuliaReach/Reachability.jl/issues/678#issuecomment-533206703.
I also added a unary version for convenience, so the old predicates would look quite similar here (except that `Atom`s have to be created explicitly and `Conjunction` is n-ary).

Tasks:
* [x] change default argument of `Conjunction`/`Disjunction`
* [x] add function-like evaluation
* [x] add module for `LazySet` predicates and try them out in practice
* [x] add documentation

### CODE REVIEW

**Comment by schillic** [comment]
> 1. Can we also add function-like evaluation for Atom, Negation, Conjunction and Disjunction ?

Sure, do you want to *only* have this way or still keep `evaluate`? I am also open to changing the name.

> 2. The parameter N corresponds to the number of arguments of the given anonymous function. Seems like redundant information for atoms. Instead of N=1 the default can be set to be N::Int=nargs(p) where nargs(p) = first(methods(p)).nargs - 1 gets the number of arguments. For conjunctions, which can have varying number of arguments, one can take the max over all arguments.

Interesting suggestions.
I do not like `first(methods(p))`. This works for anonymous functions, but in some applications you may want to pass functions with several methods it is unpredictable.
The conjunction is not always right (take `f(x, y) & g(z, w)` which expects four arguments) but it is predictable. So I would go for the second suggestion only.

> 3. What is the meaning of the Int[] arguments in the conjunctions?

The second entry contains the indices to map the predicate arguments of the whole conjunction to this conjunct. For conjuncts that do not receive any arguments, this is the empty list. This is annoying but I think generally needed. Note that we will not have to deal with that in our application because we always only use unary predicates and there is a convenience constructor for those.

> Can you add some docs?

Yes, that was my plan after we agreed on some version :grin:

> 4. Does the package need to somehow store id's (symbols or other) for the variables?

I do not understand this question, sorry.

**Comment by mforets** [comment]
> Sure, do you want to only have this way or still keep evaluate? 

I would still keep `evaluate`, it's kind of a standard name.

**Comment by mforets** [comment]
> This works for anonymous functions, but in some applications you may want to pass functions with several methods it is unpredictable.

Ok. I was assuming that the intent was to only use anonymous functions, as all the tests were like that, but that need not to be the case in general of course.

**Comment by mforets** [comment]
> The second entry contains the indices to map the predicate arguments of the whole conjunction to this conjunct.

Don't know if i still follow, so that is a map from positions to variables? My 4th point was precisely in that direction.

**Comment by mforets** [comment]
For example, suppose i have an n=10 dimensional system, and i want to specify a bad states property `x1+x3 < 10`. So one could either:

- define a 10-dimensional halfspace with normal vector `[1, 0, 1, 0, ..., 0]` and pass it to some constructor, or  (this method is what we now do in Reachability)
- define variables `:x1`, ..., `:x10` and pass the expression `x1 + x3 < 10`, and the program will create the previous halfspace automatically.

Do you have any of these approaches in mind, or something else?

**Comment by schillic** [comment]
> For example, suppose i have an n=10 dimensional system, and i want to specify a bad states property x1+x3 < 10

I would create an `Atom(X -> isdisjoint(X, H))` where `H = HalfSpace(...)`. And since this is so common, we would probably have a convenience type for such predicates.

**Pull request merged**
